app:
  network:
    blockchains:
      - name: Ethereum
        asset: ETH
        parameters:
          node-url: <ethereum-node-url>
          timeout-sec: 10

spring:
  main:
    banner-mode: off

  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:whales}'
    username: ${DB_USER}
    password: ${DB_PASS}
