app:
  network:
    enabled-networks: ${APP_ENABLED_NETWORKS:Ethereum,Ripple}
    blockchains:
      - name: Ethereum
        parameters:
          node-url: ${APP_ETHEREUM_NODE_URL}
          timeout-sec: ${APP_ETHEREUM_TIMEOUT:10}
      - name: Ripple
        parameters:
          rippled-url: ${APP_RIPPLED_URL}
      - name: Stellar
        parameters:
          horizon-url: ${APP_STELLAR_URL}
          asset: ${APP_STELLAR_ASSET:native}
      - name: Binance Chain
        parameters:
          asset: ${APP_BINANCE_ASSET:BNB}
      - name: Tron
        parameters:
          api-key: ${APP_TRON_API_KEY}
  storage-poller:
    delay-generators:
      retry-delay:
        type: LIMITED_FIXED
        limited-fixed-generator:
          delay: 60s
          retry-limit: 3
      poll-delay:
        type: RANDOM
        random-generator:
          min-delay: 1s
          max-delay: 3s

spring:
  main:
    banner-mode: off

  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:whales}'
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
