app:
  network:
    enabled-networks: ${APP_ENABLED_NETWORKS:Ethereum,Ripple}
    blockchains:
      - name: Ethereum
        parameters:
          node-url: ${APP_ETHEREUM_NODE_URL}
          timeout-sec: 10
      - name: Ripple
        parameters:
          rippled-url: ${APP_RIPPLED_URL}

spring:
  main:
    banner-mode: off

  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:whales}'
    username: ${DB_USER}
    password: ${DB_PASS}
