app:
  network:
    enabled-networks: ${APP_ENABLED_NETWORKS:Ethereum,Ripple}
    blockchains:
      - name: Ethereum
        asset: ETH
        parameters:
          node-url: <ethereum-node-url>
          timeout-sec: 10
      - name: Ripple
        asset: XRP
        parameters:
          rippled-url: https://s1.ripple.com:51234/

spring:
  main:
    banner-mode: off

  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:whales}'
    username: ${DB_USER}
    password: ${DB_PASS}
